"use client";
import { Provider } from "react-redux";
import "./globals.css";
import store from "../Redux/store";

export const metadata = {
  title: {
    default: "Study Timeer",
    template: " %s | My Study Clock",
  },
  description: "Generated by lazy next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
