"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "../Redux/store";

export const metadata = {
  title: {
    default: "Study Timeer",
    template: " %s | My Study Clock",
  },
  description: "Generated by lazy next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
